name: Release Pipeline

on:
  release:
    types: [published]

jobs:
  build-nix:
    env:
      IN_PIPELINE: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        type: [ubuntu-x64, ubuntu-x86, armv7, aarch64]
        include:
          - type: ubuntu-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: rustscan-x86_64-linux
            path: target/x86_64-unknown-linux-musl/release/rustscan
          - type: ubuntu-x86
            os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: rustscan-x86-linux
            path: target/i686-unknown-linux-musl/release/rustscan
          - type: armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            name: rustscan-armv7-linux
            path: target/armv7-unknown-linux-gnueabihf/release/rustscan
          - type: aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: rustscan-aarch64-linux
            path: target/aarch64-unknown-linux-gnu/release/rustscan
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
      - name: Package and Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.path }}
            ${{ matrix.name }}.tar.gz

  build-deb:
    needs: [build-nix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo deb --target=x86_64-unknown-linux-musl
      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/debian/rustscan_*.deb

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --target x86_64-apple-darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-apple-darwin/release/rustscan
            rustscan-x86_64-macos.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --target x86_64-pc-windows-msvc
      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-pc-windows-msvc/release/rustscan.exe
